name: CI/CD workflow

on: workflow_dispatch

# given: workflow-level env vars (see "Workflow contexts" below)
env:
  AWS_REGION: us-east-1 # your region (e.g. us-east-1)
  ECR_REPOSITORY: sentiment-app-onnx  # must match the repository created in Exercise 1

# defaults:
#   run:
#     working-directory: lab11

jobs:
  integration:
    name: checks_and_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        # given: checks out your repository code so the workflow can access it
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # remove this line for personal accounts
          aws-region: ${{ env.AWS_REGION }}

      - name: Show run info
        run: |
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"

      - name: Show region
        run: echo "Deploying to ${{ env.AWS_REGION }}"

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        # TODO: sync ONLY the `integration` group dependencies
        run: uv sync --group integration

      - name: Run ruff
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest tests/ -v

      - name: Prepare model from HuggingFace Hub
        run: uv run python -m src.scripts.prepare_model_from_hf

      - name: Export model to ONNX
        run: uv run python -m src.scripts.export_zeroshot_to_onnx

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build and Push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REPOSITORY:$IMAGE_TAG .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
