name: AWS Deployment

on: workflow_dispatch

# given: workflow-level env vars (see "Workflow contexts" below)
env:
  AWS_REGION: us-east-1 # your region (e.g. us-east-1)
  ECR_REPOSITORY: sentiment-app-onnx  # must match the repository created in Exercise 1
jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        # given: checks out your repository code so the workflow can access it
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # remove this line for personal accounts
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --group deployment

      - name: Prepare model from HuggingFace Hub
        run: uv run python -m src.scripts.prepare_model_from_hf

      - name: Export model to ONNX
        run: uv run python -m src.scripts.export_zeroshot_to_onnx

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build and Push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REPOSITORY:$IMAGE_TAG .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Delete stack if in rollback state
        run: bash scripts/recover_rollback.sh
        env:
          STACK_NAME: sentiment-app-stack
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Resolve Lambda role ARN from name
        id: lambda_role
        run: bash scripts/resolve_lambda_role.sh
        env:
          ROLE_NAME: ${{ secrets.ROLE_NAME }}

      - name: Deploy with AWS SAM
        run: bash scripts/sam_deploy.sh
        env:
          STACK_NAME: sentiment-app-stack
          AWS_REGION: ${{ env.AWS_REGION }}
          IMAGE_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          LAMBDA_ROLE_ARN: ${{ steps.lambda_role.outputs.role_arn }}



